info:
  app:
    name: tips-spring-profiles
    version: 0.0.1

spring:
  application:
    name: ${info.app.name}
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

---

spring:
  profiles: test


server.port: 10001

---

spring:
  profiles: qa

server.port: 20001

---

spring:
  profiles: prod

server.port: 30001

---

spring:
  profiles: h2-mem
  jpa:
    database: h2
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:

---

spring:
  profiles: h2-embedded
  jpa:
    database: h2
  datasource:
    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: qa
    password: password

---

spring:
  profiles: h2-server
  jpa:
    database: h2
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: prod
    password: password
